package com.henc.geoserver;

public enum GeoserverOperationStatus {
	PUBLISH_SUCCEED, PUBLISH_FAILED, 
	ERROR, 
	MAP_EXIST, 
	STYLE_EXIST,
	REPUBLISH_SUCCEED, REPUBLISH_FAILD, 
	REMOVE_SUCCEED, REMOVE_FAILD,
	UNPUBLISH_SUCCEED,UNPUBLISH_FAILED,
	UPDATESTYLE_SUCCED,UPDATESTYLE_FAILED,
	PUBLISHSTYLE_SUCCEED,PUBLISHSTYLE_FAILED,
	REMOVESTYLE_SUCCEED,REMOVESTYLE_FAILED,
}
